services:
  backend:
    image: hvnn1606/devops_shop_backend:latest
    container_name: devops_backend
    restart: always
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - MONGO_URL=mongodb+srv://vannghia16062004_db_user:CExJdIFqOM1SunGg@clusterdevops.0tadzaa.mongodb.net/database
    depends_on:
      - mongo

  frontend:
    image: hvnn1606/devops_shop_frontend:latest
    container_name: devops_frontend
    restart: always
    ports:
      - "3000:80"

  mongo:
    image: mongo:6
    container_name: devops_mongo
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
